from .algorithmic_prompt import REPEAT_COPY_PROMPT, OBJECT_COUNTING_PROMPTING
from .colored_object_prompt import COLOR_OBJECT_PROMPT
from .date_understanding_prompt import DATE_UNDERSTANDING_PROMPT
from .math_prompts import MATH_CHAT_BETA_SYSTEM_MESSAGE, MATH_CHAT_BETA_PROMPT, MATH_NOVAR_PROMPT
from .penguin_prompt import PENGUIN_PROMPT
from .baseline_prompt import DIRECT_PROMPT, DIRECT_SYSTEM_MESSAGE, COT_PROMPT, COT_SYSTEM_MESSAGE 